### ISSUE TITLE
Impl From<[u8;32]> for Commitment<T>

### ISSUE THREAD

**Issue by ggutoski** [EspressoSystems/commit#39]
Downstream users (eg. hotshot) need a way to make a `Commitment<T>` using bytes they've obtained elsewhere. Currently the only way to do that is to use `RawCommitmentBuilder`. This does an unnecessary hash on the original bytes, thus changing the commitment bytes from what the user wants.

I propose to impl `From<[u8;32]>` for `Commitment<T>`.

**Comment by jbearer** [comment]
Not implementing `From<[u8; 32]>` was an intentional decision, because in most cases you _should_ only be using `RawCommitmentBuilder` to build a commitment, and `From` in Rust is unfortunately easy to use implicitly or without even realizing it's being used.

Making a commitment using bytes obtained elsewhere sounds a lot like deserializing, so I would recommend using `CanonicalDeserialize`, which for `Commitment<T>` will always read exactly 32 bytes and convert it directly to a commitment without extra hashing. Essentially it does exactly what `From<[u8; 32]>` would do, but with an API that is harder to use by accident.

**Comment by ggutoski** [comment]
I didn't know this is possible. Thanks for pointing that out. I guess this means the `default_commitment_no_preimage` added in #37 is redundant. It's pretty ugly -- we should probably delete it.

**Comment by jbearer** [comment]
Hmm. I might keep it. For `Commitment<T>` in particular, deserializing the array `[0; 32]` is a good default. Not sure we want to require that for every implementor of `CommitmentBounds`, because that basically requires that your implementation is isomorphic to `[u8; 32]`

**Comment by ggutoski** [comment]
Ok sounds good.

Note that your [suggestion](https://github.com/EspressoSystems/commit/issues/39#issuecomment-1741455344) forces us to add `CanonicalDeserialize` to `CommitmentBounds`, and downstream users now need to know about it.

**Comment by jbearer** [comment]
Yeah, i think requiring commitments to be serializable is reasonable. We could avoid relying on arkworks specifically by adding serialization functions to the CommitmentBounds trait, which for Commitment itself would happen to use arkworks entirely. Not sure if its worth the extra boilerplate though
